### ISSUE TITLE
Migration job failing when run in dev gcp cluster and locally

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/genegraph#222]
Trying to run a genegraph migration in fulfillment of Genegraph #219.

This is also a place holder for discussion around how to handle these kinds of failures in parity builds (where genegraph container is built along with migration run).

This failing consistently with the same 403 error, but not always on the same file.

Although my local run and cloud run both failed on https://storage.googleapis.com/gnomad-public/release/2.1.1/constraint/gnomad.v2.1.1.lof_metrics.by_gene.txt.bgz.

12:06:43.391 [clojure-agent-send-off-pool-8] INFO  genegraph.sink.fetch  - {:fn :fetch-data, :msg :retrieving, :url "https://storage.googleapis.com/gnomad-public/release/2.1.1/constraint/gnomad.v2.1.1.lof_metrics.by_gene.txt.bgz", :line 65}
Exception in thread "main" java.util.concurrent.ExecutionException: clojure.lang.ExceptionInfo: clj-http: status 403 {:cached nil, :request-time 1806, :repeatable? false, :protocol-version {:name "HTTP", :major 1, :minor 1}, :streaming? true, :http-client #object[org.apache.http.impl.client.InternalHttpClient 0x40ee664c "org.apache.http.impl.client.InternalHttpClient@40ee664c"], :chunked? false, :type :clj-http.client/unexceptional-status, :reason-phrase "Forbidden", :headers {"Server" "Apache", "Upgrade" "h2,h2c", "Content-Type" "text/plain; charset=utf-8", "X-Content-Type-Options" "nosniff", "Content-Length" "134", "X-Frame-Options" ["sameorigin" "DENY"], "Strict-Transport-Security" "max-age=31536000; includeSubDomains", "Connection" "Upgrade, close", "Set-Cookie" "sessionid=d73v2qsot3je9idtf1h0enk7rfy9bb3h; HttpOnly; Path=/; SameSite=Strict; Secure", "ETag" "\"MTYyNDk1MjM4Mi4w\"", "Date" "Tue, 29 Jun 2021 12:06:34 GMT", "Vary" "Cookie", "Last-Modified" "Tue, 29 Jun 2021 07:39:42 GMT", "X-XSS-Protection" "1; mode=block", "Content-Security-Policy" "upgrade-insecure-requests"}, :orig-content-encoding nil, :status 403, :length 134, :body #object["[B" 0x52072c45 "[B@52072c45"], :trace-redirects []}
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at clojure.core$deref_future.invokeStatic(core.clj:2300)
	at clojure.core$future_call$reify__8454.deref(core.clj:6974)
	at clojure.core$deref.invokeStatic(core.clj:2320)
	at clojure.core$pmap$step__8467$fn__8471.invoke(core.clj:7025)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:713)
	at clojure.core$next__5386.invokeStatic(core.clj:64)
	at clojure.core$dorun.invokeStatic(core.clj:3142)
	at clojure.core$doall.invokeStatic(core.clj:3148)
	at clojure.core$doall.invoke(core.clj:3148)
	at genegraph.sink.base$retrieve_base_data_BANG_.invokeStatic(base.clj:40)
	at genegraph.sink.base$retrieve_base_data_BANG_.invoke(base.clj:39)
	at genegraph.sink.base$initialize_db_BANG_.invokeStatic(base.clj:53)
	at genegraph.sink.base$initialize_db_BANG_.invoke(base.clj:51)
	at genegraph.migration$build_database$fn__31176.invoke(migration.clj:70)
	at clojure.core$with_redefs_fn.invokeStatic(core.clj:7514)
	at clojure.core$with_redefs_fn.invoke(core.clj:7498)
	at genegraph.migration$build_database.invokeStatic(migration.clj:67)
	at genegraph.migration$build_database.invoke(migration.clj:63)
	at genegraph.migration$create_migration.invokeStatic(migration.clj:117)
	at genegraph.migration$create_migration.invoke(migration.clj:111)
	at genegraph.server$_main.invokeStatic(server.clj:71)
	at genegraph.server$_main.doInvoke(server.clj:52)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at genegraph.server.main(Unknown Source)

**Comment by toneillbroad** [comment]
In further testing, migration still failing and direct downloading of OMIM failing with 429 status and message "This data account exceeded its download cap, please contact us at https://omim.org/contact if this is an issue"˚. Keeping this ticket open until a successful migration.

**Comment by toneillbroad** [comment]
Further issues after the OMIM "forbidden": was getting clojure.lang.ExceptionInfo: clj-http: status 404 on one of the files. Determined it to be "gnomad_v2.1.1.lof_metrics_by_gene.txt.gz" and needed to update the URL in base.edn.
